treatments:
  - name: one
    factorIds:
      - Gp6JtPM3bmcMW3BM6
factorTypes:
  - _id: dFWFKk8FDx7x3ySmh
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
factors:
  - _id: Gp6JtPM3bmcMW3BM6
    name: one
    value: 1
    factorTypeId: dFWFKk8FDx7x3ySmh
lobbyConfigs:
  - timeoutType: lobby
    timeoutInSeconds: 300
    timeoutStrategy: fail
    gameLobbyIds: []
