treatments:
  - name: debug_one
    factorIds:
      - QyrjYNGnacDJunnk4
      - 7fsHrmRDLSEu5fA55
      - tjPeajmkzhezsdZiP
  - name: debug_two
    factorIds:
      - DX8hyBrNJjySgZqsL
      - 7fsHrmRDLSEu5fA55
      - tjPeajmkzhezsdZiP
  - name: debug_ten
    factorIds:
      - n3qyCSkh6t5THNhg8
      - 7fsHrmRDLSEu5fA55
      - tjPeajmkzhezsdZiP
factorTypes:
  - _id: qsYM4pi6vDr6nkzuh
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: FodcdvBwWByyq2Tgt
    name: stageDuration
    description: stage duration
    required: false
    type: Integer
  - _id: d67nv8BP8K2ptpiN7
    name: roundNum
    description: number of rounds
    required: false
    type: String
    min: 1
    max: 3
factors:
  - _id: QyrjYNGnacDJunnk4
    name: one
    value: 1
    factorTypeId: qsYM4pi6vDr6nkzuh
  - _id: DX8hyBrNJjySgZqsL
    name: two
    value: 2
    factorTypeId: qsYM4pi6vDr6nkzuh
  - _id: n3qyCSkh6t5THNhg8
    name: ten
    value: 10
    factorTypeId: qsYM4pi6vDr6nkzuh
  - _id: nrvnWLrbnps72P9SJ
    name: 5min
    value: 300
    factorTypeId: FodcdvBwWByyq2Tgt
  - _id: 7fsHrmRDLSEu5fA55
    name: debug
    value: 3000
    factorTypeId: FodcdvBwWByyq2Tgt
  - _id: tjPeajmkzhezsdZiP
    name: one
    value: '1'
    factorTypeId: d67nv8BP8K2ptpiN7
lobbyConfigs:
  - timeoutType: lobby
    timeoutInSeconds: 300
    timeoutStrategy: ignore
    gameLobbyIds: []
